# Generated by Django 4.2.24 on 2026-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_amount_invoice_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='work_description',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='amount',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(),
        ),
    ]
