# Generated by Django 4.2.24 on 2026-01-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_subtotal_remove_invoice_vat_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='work_description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
